# Generated by Django 6.0.4 on 2026-05-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_compatibility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='severity_level',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], default='high', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('carbohydrate', 'Carbohydrate'), ('protein', 'Protein'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('meat', 'Meat'), ('fastFood', 'FastFood'), ('grain', 'Grain'), ('dairy', 'Dairy'), ('spice', 'Spice'), ('beverage', 'Beverage'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
