# Generated by Django 6.0.4 on 2026-05-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status_alter_doctor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_signature',
            field=models.ImageField(blank=True, help_text="Doctor's digital signature", null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_image',
            field=models.ImageField(blank=True, help_text='Upload prescription image', null=True, upload_to='prescriptions/'),
        ),
    ]
