# Generated by Django 6.0.4 on 2026-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_prescription_doctor_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimeslot',
            name='max_patients',
            field=models.PositiveIntegerField(default=5, help_text='Maximum patients in this time slot'),
        ),
    ]
