# Generated by Django 6.0.4 on 2026-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_doctortimeslot_max_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortimeslot',
            name='max_patients',
            field=models.PositiveIntegerField(default=5, help_text='Maximum patients allowed in this slot'),
        ),
    ]
