# Generated by Django 6.0.4 on 2026-05-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_doctortimeslot_max_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_spots',
        ),
        migrations.AddField(
            model_name='doctor',
            name='daily_max_patients',
            field=models.PositiveIntegerField(default=10, help_text='Maximum patients per day'),
        ),
        migrations.AlterField(
            model_name='doctortimeslot',
            name='max_patients',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
