# Generated by Django 6.0.4 on 2026-05-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_doctor_available_spots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctortimeslot',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AlterField(
            model_name='doctortimeslot',
            name='max_patients',
            field=models.PositiveIntegerField(default=10, help_text='Maximum patients for this time slot'),
        ),
    ]
