# Generated by Django 6.0.4 on 2026-04-27 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Medicine name', max_length=200)),
                ('dosage_amount', models.DecimalField(decimal_places=2, help_text='Amount per dose', max_digits=6)),
                ('dosage_unit', models.CharField(choices=[('tablet', 'Tablet(s)'), ('capsule', 'Capsule(s)'), ('ml', 'ML'), ('mg', 'MG'), ('drops', 'Drop(s)'), ('teaspoon', 'Teaspoon(s)'), ('tablespoon', 'Tablespoon(s)')], default='tablet', max_length=20)),
                ('frequency', models.CharField(choices=[('once', 'Once Daily'), ('twice', 'Twice Daily'), ('thrice', 'Three Times Daily'), ('four', 'Four Times Daily'), ('custom', 'Custom Times')], default='once', max_length=10)),
                ('food_timing', models.CharField(choices=[('any', 'No Preference'), ('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], default='any', max_length=10)),
                ('start_date', models.DateField(help_text='When to start taking this medicine')),
                ('end_date', models.DateField(help_text='When to stop taking this medicine')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions (e.g., take with food)')),
                ('doctor_name', models.CharField(blank=True, help_text='Name of prescribing doctor', max_length=200)),
                ('prescription_date', models.DateField(blank=True, help_text='Date prescribed by doctor', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Time to take medicine')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_times', to='medicine_reminders.medicine')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='DoseTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('time_taken', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_reminders.medicine')),
                ('reminder_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_reminders.remindertime')),
            ],
            options={
                'ordering': ['-date_taken', '-time_taken'],
                'unique_together': {('medicine', 'reminder_time', 'date_taken')},
            },
        ),
    ]
