# Generated by Django 6.0.4 on 2026-04-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('is_taken', models.BooleanField(default=False)),
                ('taken_at', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reminders', to='medicine_reminders.medicine')),
                ('reminder_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_reminders.remindertime')),
            ],
            options={
                'ordering': ['-reminder_date', 'reminder_time'],
                'unique_together': {('medicine', 'reminder_date', 'reminder_time')},
            },
        ),
    ]
