# Generated by Django 6.0.4 on 2026-04-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminders', '0002_medicinereminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineReminder',
        ),
    ]
