# Generated by Django 6.0.4 on 2026-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminders', '0004_notificationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='prescription_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='remindertime',
            name='time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
