# Generated by Django 6.0.4 on 2026-04-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminders', '0005_alter_medicine_options_alter_medicine_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once Daily'), ('twice', 'Twice Daily'), ('thrice', 'Three Times Daily'), ('four', 'Four Times Daily')], default='once', max_length=10),
        ),
    ]
