# Generated by Django 6.0.4 on 2026-05-04 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminders', '0006_alter_medicine_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_url', models.URLField(max_length=500)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='medicine_reminders.medicine')),
                ('reminder_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_reminders.remindertime')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('medicine', 'reminder_time')},
            },
        ),
    ]
