# Generated by Django 6.0.4 on 2026-05-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminders', '0007_googlecalendarevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlecalendarevent',
            options={'ordering': ['-synced_at']},
        ),
        migrations.RemoveField(
            model_name='googlecalendarevent',
            name='calendar_url',
        ),
        migrations.RemoveField(
            model_name='googlecalendarevent',
            name='created_at',
        ),
        migrations.AddField(
            model_name='googlecalendarevent',
            name='calendar_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='googlecalendarevent',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='googlecalendarevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='synced_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
