# Generated by Django 6.0.4 on 2026-05-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminders', '0008_alter_googlecalendarevent_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleCalendarEvent',
        ),
    ]
